import {PDFDocument,rgb,PDFFont} from 'pdf-lib';
import fontkit from '@pdf-lib/fontkit';
import fontBytes from './fonts/NotoSansSC.ttf';
import type {OfficePdfSnapshot} from 'workdsh-contracts/office';
import {pdfStateSchema} from './model.js';
const color=(hex:string)=>rgb(...[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255) as [number,number,number]);
function lines(text:string,font:PDFFont,size:number,width:number){const output:string[]=[],supported=new Set(font.getCharacterSet()),cache=new Map<string,number>();for(const paragraph of text.split('\n')){let line='',used=0;for(const ch of paragraph){if(!supported.has(ch.codePointAt(0)!))throw Error(`PDF 字体不支持字符 ${ch}，请更换文字。`);const advance=cache.get(ch)??font.widthOfTextAtSize(ch,size);cache.set(ch,advance);if(advance>width)throw Error('PDF 文本框过窄。');if(line&&used+advance>width){output.push(line);line=ch;used=advance;}else{line+=ch;used+=advance;}}output.push(line);}return output;}

export async function pdfBytes(snapshot:OfficePdfSnapshot,signal?:AbortSignal){signal?.throwIfAborted();const state=pdfStateSchema.parse(snapshot.state),doc=await PDFDocument.create();doc.registerFontkit(fontkit);doc.setTitle(snapshot.title);doc.setCreator('开物Praxis');const fixed=new Date('2026-01-01T00:00:00Z');doc.setCreationDate(fixed);doc.setModificationDate(fixed);const font=await doc.embedFont(fontBytes,{subset:false});for(const p of state.pages){signal?.throwIfAborted();const page=doc.addPage([p.width,p.height]);page.drawRectangle({x:0,y:0,width:p.width,height:p.height,color:color(p.background)});for(const e of p.elements){if(e.type==='rectangle')page.drawRectangle({x:e.x,y:p.height-e.y-e.height,width:e.width,height:e.height,color:color(e.fill)});else{const wrapped=lines(e.text,font,e.fontSize,e.width),step=e.fontSize*e.lineHeight;if(e.text&&wrapped.length*step>e.height)throw Error(`PDF 文本框 ${e.id} 内容溢出，请增加高度、减小字号或拆页。`);wrapped.forEach((line,i)=>{if(line)page.drawText(line,{x:e.x,y:p.height-e.y-e.fontSize-i*step,size:e.fontSize,font,color:color(e.color)});});}}}return doc.save();}
