import React from 'react';
import {createRoot} from 'react-dom/client';
import {PowerPointViewer,Toolbar,SlideCanvas,useViewerBuildingBlocks} from 'pptx-react-viewer';
import 'pptx-react-viewer/styles';
import {PptxHandler} from 'pptx-viewer-core';
import i18next from 'i18next';
import {I18nextProvider} from 'react-i18next';
import {translationsEn,keyToLabel} from 'pptx-react-viewer/i18n';
const labels:Record<string,string>={"Slides":"幻灯片","Insert":"插入","Format":"格式","Comments":"批注","Notes":"备注","File":"文件","Home":"开始","Design":"设计","Transitions":"切换","Animations":"动画","Slide Show":"放映","View":"视图","Review":"审阅","Draw":"绘图","Text":"文字","Undo":"撤销","Redo":"重做","Save":"保存","Save As":"另存为","Download":"下载","Export":"导出","Share":"分享","Print":"打印","Open":"打开","Close":"关闭","New":"新建","Settings":"设置","Options":"选项","Language":"语言","Appearance":"外观","All saved":"已保存","Add Slide":"添加幻灯片","New Slide":"新建幻灯片","Delete":"删除","Duplicate":"复制","Layout":"版式","Picture":"图片","Image":"图片","Table":"表格","Chart":"图表","Shape":"形状","Shapes":"形状","Font":"字体","Paragraph":"段落","Bold":"加粗","Italic":"斜体","Underline":"下划线","Size":"大小","Color":"颜色","Fill":"填充","Outline":"轮廓","Data":"数据","Title":"标题","Categories":"分类","Series":"系列","Value":"数值","Cancel":"取消","Apply":"应用","OK":"确定","Position":"位置","Width":"宽度","Height":"高度","Rotate":"旋转","Align":"对齐","Zoom":"缩放","Fit":"适应窗口","Search":"搜索","Find":"查找","Replace":"替换","Select":"选择","Selection":"选区","Presentation":"演示","Present":"放映","Arrange":"排列","Group":"组合","Ungroup":"取消组合"};
Object.assign(labels,{"Preview":"预览","None":"无","Fade":"淡化","Push":"推进","Wipe":"擦除","Split":"分割","Reveal":"揭示","Cover":"覆盖","Uncover":"移出","Duration":"持续时间","Help":"帮助","Show":"放映","Clipboard":"剪贴板","Slide Templates":"幻灯片模板","Reset":"重置","Section":"节","Editing":"编辑","Drawing":"绘图","Flip H":"水平翻转","Flip V":"垂直翻转","Back":"下移","Front":"上移","Properties":"属性","Elements":"元素","Choose Image":"选择图片","Clear Background":"清除背景","Add":"添加","Copy":"复制","Paste":"粘贴","Cut":"剪切","Format Painter":"格式刷","Font Size":"字号","Font Color":"字体颜色","Text Color":"文字颜色","Align Left":"左对齐","Align Right":"右对齐","Center":"居中","Justify":"两端对齐","Line Spacing":"行距","Normal":"普通","Fit to Window":"适应窗口","From Beginning":"从头放映","From Current Slide":"从当前页放映"});
Object.assign(labels,{"Browse Themes":"浏览主题","Edit Theme":"编辑主题","Slide Size":"页面大小","Format Background":"设置背景格式","Browse and apply built-in themes":"浏览并应用内置主题","Edit theme - theme editor not yet ported":"主题编辑尚未接入","Slide size / document properties":"页面大小与文档属性","Format slide background - opens the Inspector":"设置背景格式（打开属性面板）","Inspector":"属性面板","Duration:":"持续时间：","After:":"之后：","Sound:":"声音：","[No Sound]":"无声音","Other Sound...":"其他声音…","Advance Slide":"换片方式","On Mouse Click":"单击鼠标时","Preview transition":"预览切换效果","Transition duration in seconds":"切换持续时间（秒）","Apply transition to all slides":"应用切换到所有幻灯片","Advance after specified duration":"在指定时间后换片","Remove Animation":"删除动画","Font family":"字体","Font size":"字号","Grow font":"增大字号","Shrink font":"减小字号","Clear formatting":"清除格式","Font colour":"字体颜色","Custom colour...":"自定义颜色…","Text highlight colour":"文字突出显示颜色","Bullet list":"项目符号","Find and replace":"查找和替换","Set Up Show":"设置放映","Set up how the show runs":"设置幻灯片放映方式","Accessibility":"辅助功能","Compare":"比较","Compare with another presentation":"与另一份演示文稿比较","Link":"链接","Shortcuts":"快捷键","Keyboard shortcut reference":"键盘快捷键说明","Toggle grid overlay":"显示或隐藏网格","Guides":"参考线","Toggle center guide lines":"显示或隐藏中心参考线","Snap elements to grid while moving":"移动元素时对齐网格","Templates On":"显示模板","Templates Off":"隐藏模板","Edit inherited master/layout (template) elements":"编辑母版或版式元素","Eyedropper":"取色器","Pick colour from screen (EyeDropper)":"从屏幕取色","Colour":"颜色","Pen colour":"画笔颜色","Stroke width":"线条宽度","Fwd":"前移","Bwd":"后移","Align left":"左对齐","Align center":"水平居中","Align right":"右对齐","Align top":"顶端对齐","Align middle":"垂直居中","Align bottom":"底端对齐","Distribute horizontally":"横向分布","Distribute vertically":"纵向分布","Equation":"公式","Column":"柱状图","Bar":"条形图","Line":"折线图","Pie":"饼图","Doughnut":"环形图","Area":"面积图","Scatter":"散点图","Bubble":"气泡图","Radar":"雷达图","Stock":"股价图","Waterfall":"瀑布图","Combo":"组合图","Clustered":"簇状","Stacked":"堆积","Default":"默认","Light (Vermilion)":"浅色主题","Dark (Vermilion)":"深色主题"});
Object.assign(labels,{"Chart type":"图表类型","Chart title":"图表标题","Grouping":"分组方式","Series colours":"系列颜色","Clear series colour":"清除系列颜色","Display":"显示","Show title":"显示标题","Show legend":"显示图例","Legend Position":"图例位置","Show gridlines":"显示网格线","Show data labels":"显示数据标签","Data labels":"数据标签","Label Position":"标签位置","Add category":"添加分类","Remove last category":"删除末尾分类","Cat":"分类","Add series":"添加系列","Remove last series":"删除末尾系列","Remove series":"删除系列","Chart filters":"图表筛选","Remove category":"删除分类","Axes":"坐标轴","Min":"最小值","Max":"最大值","Major":"主要单位","Minor":"次要单位","Display Units":"显示单位","Auto":"自动","Axis title":"坐标轴标题","Ticks":"刻度","Major gridlines":"主要网格线","Minor gridlines":"次要网格线","Axis styling":"坐标轴样式","Log scale":"对数刻度","Log base":"对数底数","Title font":"标题字体","Media":"媒体","Effects":"效果","Soft Edge":"柔化边缘","Soft Edge Radius":"柔化半径","Position & Size":"位置和大小","Lock element":"锁定元素","Unlock element":"解锁元素","Rotation":"旋转","Opacity":"不透明度","Background":"背景","Background Color":"背景颜色","Slide Properties":"幻灯片属性","Slide Number":"幻灯片编号","Aspect Ratio":"宽高比","Landscape":"横向","Portrait":"纵向","Solid":"纯色","Gradient":"渐变","Pattern":"图案","Transparency":"透明度","Border":"边框","Spacing":"间距","Margins":"边距","Left":"左","Right":"右","Top":"上","Bottom":"下","Inside":"内部","Outside":"外部","Percentage":"百分比","Category Name":"分类名称","Series Name":"系列名称","Show Value":"显示数值","Legend":"图例","Select a chart to edit its properties.":"选择图表以编辑属性。","This chart has no editable data.":"此图表没有可编辑的数据。","No chart data available.":"没有可用的图表数据。"});
Object.assign(labels,{Entrance:'进入',Emphasis:'强调',Exit:'退出',Element:'元素',Animations:'动画','Motion Path':'动作路径','Series 1':'系列1','Category 1':'分类1'});
Object.assign(labels,{'Alt text':'替代文字','Describe this element for accessibility':'描述此元素，便于辅助功能识别','Accessibility title':'辅助功能标题','Accessibility title (optional)':'辅助功能标题（可选）',Action:'动作','On Click':'单击时','On Hover':'悬停时',Transform:'变换','Layer Order':'图层顺序','Slide comments':'幻灯片批注','No comments':'暂无批注','No comments on this slide yet.':'此页暂无批注','Commenting on:':'批注对象：','Add Comment':'添加批注','Add a comment...':'输入批注…','Bar (3-D)':'三维条形图','Line (3-D)':'三维折线图','Pie (3-D)':'三维饼图','Area (3-D)':'三维面积图',Surface:'曲面图',Histogram:'直方图',Pareto:'帕累托图',Funnel:'漏斗图',Treemap:'矩形树图',Sunburst:'旭日图','Box and Whisker':'箱线图','Filled Map':'填充地图','Pie of Pie':'复合饼图',Unknown:'未知',Picture:'图片',Object:'对象',Connector:'连接线',Group:'组合'});
const normalized=new Map(Object.entries(labels).map(([k,v])=>[k.toLowerCase(),v]));
const translationsZh=Object.fromEntries(Object.entries(translationsEn).filter(([k,v])=>normalized.has(v.toLowerCase())).map(([k,v])=>[k,normalized.get(v.toLowerCase())]));
Object.assign(translationsZh,{'pptx.statusBar.slideOf':'第 {{current}} 页 / 共 {{total}} 页','pptx.presenter.slideLabel':'第 {{current}} 页 / 共 {{total}} 页','pptx.ribbon.fontColourValue':'字体颜色 {{color}}','pptx.ribbon.highlightColourValue':'突出显示颜色 {{color}}','pptx.ribbon.fillColourValue':'填充颜色 {{color}}','pptx.ribbon.outlineColourValue':'轮廓颜色 {{color}}','pptx.customShows.addShow':'+ 新建放映','pptx.comments.addOnElement':'为{{element}}输入批注…','pptx.comments.commentingOn':'批注对象：{{element}}','pptx.inspector.rotation':'旋转（°）'});
(window as any).translationCoverage={translated:Object.keys(translationsZh).length,total:Object.keys(translationsEn).length};
await i18next.init({lng:'zh-CN',fallbackLng:'en',resources:{en:{translation:translationsEn},'zh-CN':{translation:translationsZh}},parseMissingKeyHandler:(key:string)=>labels[keyToLabel(key)]??keyToLabel(key),interpolation:{escapeValue:false}});
const editorTheme={colors:{background:'#111213',foreground:'#ededee',card:'#222326',cardForeground:'#ededee',popover:'#242528',popoverForeground:'#ededee',primary:'#1677ff',primaryForeground:'#ffffff',secondary:'#202124',secondaryForeground:'#ededee',muted:'#2a2b2f',mutedForeground:'#a5a6ad',accent:'#303236',accentForeground:'#ffffff',border:'#3b3d42',input:'#44464c',ring:'#1677ff'},radius:'0.375rem'};
const ref=React.createRef<any>();
const root=createRoot(document.getElementById('host')!);
(window as any).api=()=>ref.current;
(window as any).events=[];
const render=(content:Uint8Array)=>root.render(<I18nextProvider i18n={i18next}><PowerPointViewer theme={editorTheme} ref={ref} content={content} canEdit defaultLocale="zh-CN" onLocaleChange={code=>{void i18next.changeLanguage(code)}} hiddenActions={['share','broadcast','record']} fileName="工作日报体验样板.pptx"/></I18nextProvider>);
(window as any).reopen=render;
(window as any).dispose=()=>root.unmount();
(window as any).inspect=async(bytes:number[])=>{const d=await new PptxHandler().load(new Uint8Array(bytes).buffer);return d.slides.map(s=>({texts:s.elements.filter(e=>e.type==='text').map(e=>(e as any).text),charts:s.elements.filter(e=>e.type==='chart').map(e=>(e as any).chartData)}));};

const {handler,data,createSlide}=await PptxHandler.create({title:'工作日报 · 中文体验样板'});
const blue='#2563EB',ink='#172554';
const text=(b:any,t:string,x:number,y:number,w:number,h:number,size=24,color=ink,bold=false)=>b.addText(t,{x,y,width:w,height:h,fontSize:size,color,bold,fontFamily:'Microsoft YaHei'});
const card=(b:any,x:number,y:number,w:number,h:number,color='#EFF6FF')=>b.addShape('rect',{x,y,width:w,height:h,fill:{type:'solid',color},stroke:{color,width:0}});
const titles=['工作日报','今日成果总览','功能完成情况','已完成工作','风险与待办','下一步计划'];
for(let i=0;i<6;i++){
 const b=createSlide();card(b,0,0,960,540,'#FFFFFF');card(b,45,38,6,40,blue);text(b,titles[i],65,35,820,60,32,ink,true);
 text(b,'开物Praxis · 体验样板（演示数据）',50,495,650,24,12,'#64748B');text(b,`${i+1} / 6`,845,495,75,24,12,'#64748B');
 if(i===0){text(b,'让成果清楚可见',65,155,480,70,40,ink,true);text(b,'计划 10 项 · 完成 7 项 · 待完成 3 项',65,260,500,70,24);card(b,650,145,245,280,blue);text(b,'70%',675,215,210,110,66,'#FFFFFF',true);text(b,'今日完成率',675,335,210,40,22,'#FFFFFF');}
 if(i===1){for(const [j,num,label] of [[0,'10','计划功能'],[1,'7','完成交付'],[2,'70%','完成率']] as const){card(b,60+j*285,140,260,270,j===1?blue:'#EFF6FF');text(b,num,85+j*285,200,210,110,64,j===1?'#FFFFFF':blue,true);text(b,label,85+j*285,330,210,45,22,j===1?'#FFFFFF':ink);}}
 if(i===2){b.addChart('pie',{categories:['已完成','待完成'],series:[{name:'功能数量',values:[7,3]}],title:'计划功能完成情况',hasLegend:true},{x:70,y:115,width:500,height:330});text(b,'7 项已完成',635,170,270,60,30,blue,true);text(b,'3 项待完成',635,260,270,60,30);text(b,'演示数据：7 ÷ 10 = 70%',635,345,270,65,20,'#64748B');}
 if(i>=3){const rows=i===3?['交付内容：按功能整理成果','验证结果：列出已完成验收','成果记录：保留文件与版本']:i===4?['待完成：3 项功能继续推进','风险：补齐实际项目明细','待办：确认负责人和时间']:['优先完成剩余功能','补充测试与交付说明','复盘成果并更新计划'];rows.forEach((r,j)=>{card(b,65,135+j*105,825,85);text(b,String(j+1).padStart(2,'0'),85,155+j*105,60,45,24,blue,true);text(b,r,165,155+j*105,690,50,24);});}
 data.slides.push(b.build());
}
const previews=await handler.exportSlides(data.slides,{format:'svg',includeHidden:true});
(window as any).slidePreviews=Array.from(previews.values()).map(bytes=>'data:image/svg+xml;base64,'+btoa(Array.from(bytes).map(b=>String.fromCharCode(b)).join('')));
render(await handler.save(data.slides));
