import { randomUUID } from 'node:crypto';
import { Context, Service } from '@deepseek-ai/cordis';
import type { KvTable } from '@deepseek-ai/dsh-storage-domain';
import type { ActorContext } from 'workdsh-contracts';
import type { CreateProjectInput, Project, ProjectActivity, ProjectAssetRef, ProjectCapabilityRef, ProjectConfig, ProjectConfigRevision, ProjectInputRef, ProjectService, ProjectSnapshot, ProjectTaskContext, ProjectTaskLink, ProjectTemplate, ProjectWorkItem } from 'workdsh-contracts/projects';
import { PROJECT_INSTRUCTION_TOKEN_BUDGET, estimateProjectInstructionTokens } from '../instruction-budget.js';
import { projectDomainSpec, projectStateKey, type ProjectState } from '../storage/domain.js';
declare module '@deepseek-ai/cordis' { interface Context { workdshProjects: ProjectService; } }
const timestamp = () => new Date().toISOString();
const clean = (value: string, code = 'projects/invalid-name', max = 10_000) => { const next = value.trim(); if (!next || next.length > max) throw new Error(code); return next; };
const templates: readonly ProjectTemplate[] = [
  { id: 'product', name: '产品需求全流程', description: '从需求规划、PRD 到研发测试验收', instruction: '围绕产品目标维护需求、计划、任务、资产和决策记录。' },
  { id: 'research', name: '市场调研与竞品分析', description: '深度调研、竞品拆解、报告评审', instruction: '引用可核验资料，区分事实、推断与建议，持续沉淀研究资产。' },
  { id: 'knowledge', name: '团队知识库', description: '持续沉淀 SOP、经验和 FAQ', instruction: '优先复用协同空间资产，输出可维护、可追溯的团队知识。' },
  { id: 'delivery', name: '协同空间交付', description: '管理客户需求、计划、风险和周报', instruction: '跟踪交付范围、负责人、时间、风险和验收证据。' },
  { id: 'bugs', name: 'Bug 跟踪/测试验收', description: '持续跟踪 Bug、测试用例和验收', instruction: '问题必须关联复现步骤、负责人、优先级、状态和验证证据。' },
];
type Stored = ProjectState & { projects: Record<string, Project>; configs: Record<string, ProjectConfigRevision>; workItems: Record<string, ProjectWorkItem>; assets: Record<string, ProjectAssetRef>; tasks: Record<string, ProjectTaskLink>; activity: Record<string, ProjectActivity> };
export class ProjectManager extends Service implements ProjectService {
  static inject = ['storageDomain']; private table?: KvTable<string, ProjectState>; private serial: Promise<unknown> = Promise.resolve();
  constructor(ctx: Context) { super(ctx, 'workdshProjects'); }
  async [Service.init]() { const domain = await this.ctx.storageDomain.open(projectDomainSpec); this.table = domain.table('states'); this.ctx.effect(() => () => domain.close(), 'workdshProjects.domainClose'); }
  templates() { return Promise.resolve(templates); }
  list(actor: ActorContext, query = '') { return this.listForStatus(actor,query,'active'); }
  listArchived(actor: ActorContext, query = '') { return this.listForStatus(actor,query,'archived'); }
  create(actor: ActorContext, input: CreateProjectInput) { return this.enqueue(async () => { const state = await this.state(actor); const template = input.templateId ? templates.find(row => row.id === input.templateId) : undefined; if (input.templateId && !template) throw new Error('projects/template-not-found'); const now = timestamp(), projectId = randomUUID(), configId = randomUUID(); const project: Project = { id: projectId, name: clean(input.name), description: input.description?.trim() || template?.description || '', ...(template ? { templateId: template.id } : {}), owner: { organizationId: actor.organizationId, ownerPrincipalId: actor.principalId, scope: 'personal' }, status: 'active', configRevisionId: configId, createdAt: now, updatedAt: now }; const config: ProjectConfigRevision = { id: configId, projectId, number: 1, instruction: template?.instruction ?? '', capabilities: [], createdBy: actor.principalId, createdAt: now }; const activity = this.event(projectId, actor, 'project', `创建了协同空间「${project.name}」`); const next = { ...state, projects: { ...state.projects, [project.id]: project }, configs: { ...state.configs, [config.id]: config }, activity: { ...state.activity, [activity.id]: activity } }; await this.put(actor,next); return this.snapshot(next,project); }); }
  get(actor: ActorContext, projectId: string) { return this.enqueue(async () => { const state=await this.state(actor); return this.snapshot(state,this.requireProject(state,projectId)); }); }
  archive(actor: ActorContext, projectId: string) { return this.enqueue(async () => { const state=await this.state(actor), current=this.requireProject(state,projectId), project={...current,status:'archived' as const,updatedAt:timestamp()}; await this.put(actor,{...state,projects:{...state.projects,[projectId]:project}}); return project; }); }
  restore(actor: ActorContext, projectId: string) { return this.enqueue(async () => { const state=await this.state(actor), stored=state.projects[projectId]; if(!stored||stored.status!=='archived')throw new Error('projects/not-found'); const current=this.normalizedProject(stored),project={...current,status:'active' as const,updatedAt:timestamp()}; const activity=this.event(projectId,actor,'project',`恢复了协同空间「${project.name}」`); await this.put(actor,{...state,projects:{...state.projects,[projectId]:project},activity:{...state.activity,[activity.id]:activity}}); return project; }); }
  updateConfig(actor: ActorContext, projectId: string, config: ProjectConfig, expectedRevisionId: string) { return this.enqueue(async () => { const state=await this.state(actor), project=this.requireProject(state,projectId), previous=state.configs[project.configRevisionId]; if (!previous || previous.id !== expectedRevisionId) throw new Error('projects/revision-conflict'); if(estimateProjectInstructionTokens(config.instruction)>PROJECT_INSTRUCTION_TOKEN_BUDGET)throw new Error('projects/instruction-budget-exceeded'); const now=timestamp(), next:ProjectConfigRevision={id:randomUUID(),projectId,number:previous.number+1,instruction:config.instruction,capabilities:[...config.capabilities],createdBy:actor.principalId,createdAt:now}; const activity=this.event(projectId,actor,'project',`更新了协同空间配置（修订 ${next.number}）`);await this.put(actor,{...state,configs:{...state.configs,[next.id]:next},projects:{...state.projects,[projectId]:{...project,configRevisionId:next.id,updatedAt:now}},activity:{...state.activity,[activity.id]:activity}}); return next; }); }
  addWorkItem(actor: ActorContext, projectId: string, title: string) { return this.enqueue(async()=>{const state=await this.state(actor);this.requireProject(state,projectId);const now=timestamp(),item:ProjectWorkItem={id:randomUUID(),projectId,title:clean(title,'projects/invalid-title',500),status:'todo',priority:'none',tags:[],revision:randomUUID(),createdAt:now,updatedAt:now};const activity=this.event(projectId,actor,'work-item',`新增计划「${item.title}」`);await this.put(actor,{...state,workItems:{...state.workItems,[item.id]:item},activity:{...state.activity,[activity.id]:activity}});return item;});}
  updateWorkItem(actor: ActorContext, projectId: string, patch: Pick<ProjectWorkItem,'id'|'title'|'status'|'assignee'|'priority'|'tags'>, expectedRevision:string) { return this.enqueue(async()=>{const state=await this.state(actor),old=state.workItems[patch.id];if(!old||old.projectId!==projectId)throw new Error('projects/not-found');if(old.revision!==expectedRevision)throw new Error('projects/revision-conflict');const item={...old,...patch,title:clean(patch.title,'projects/invalid-title',500),revision:randomUUID(),updatedAt:timestamp()};const activity=this.event(projectId,actor,'work-item',`更新计划「${item.title}」`);await this.put(actor,{...state,workItems:{...state.workItems,[item.id]:item},activity:{...state.activity,[activity.id]:activity}});return item;});}
  addAsset(actor: ActorContext, projectId:string, input:Omit<ProjectAssetRef,'id'|'projectId'|'createdAt'>){return this.enqueue(async()=>{const state=await this.state(actor);this.requireProject(state,projectId);const existing=Object.values(state.assets).find(row=>row.projectId===projectId&&row.assetId===input.assetId&&row.revisionId===input.revisionId);if(existing)return existing;const ref:ProjectAssetRef={...input,id:randomUUID(),projectId,createdAt:timestamp()};const activity=this.event(projectId,actor,'asset',`关联资产「${ref.name}」`);await this.put(actor,{...state,assets:{...state.assets,[ref.id]:ref},activity:{...state.activity,[activity.id]:activity}});return ref;});}
  removeAsset(actor:ActorContext,projectId:string,refId:string){return this.enqueue(async()=>{const state=await this.state(actor),ref=state.assets[refId];if(!ref||ref.projectId!==projectId)throw new Error('projects/not-found');const assets={...state.assets};delete assets[refId];const activity=this.event(projectId,actor,'asset',`移除资产引用「${ref.name}」`);await this.put(actor,{...state,assets,activity:{...state.activity,[activity.id]:activity}});});}
  validateInputRefs(actor:ActorContext,projectId:string,references:readonly ProjectInputRef[]){return this.enqueue(async()=>{const state=await this.state(actor),project=this.requireProject(state,projectId);return this.validateReferences(state,project,references);});}
  linkTask(actor:ActorContext,projectId:string,sessionId:string,title:string,workItemId?:string,references:readonly ProjectInputRef[]=[],_signal?:AbortSignal,capabilities?:readonly ProjectCapabilityRef[]){return this.enqueue(async()=>{const state=await this.state(actor),project=this.requireProject(state,projectId);if(workItemId&&state.workItems[workItemId]?.projectId!==projectId)throw new Error('projects/not-found');const validated=this.validateReferences(state,project,references);const configured=state.configs[project.configRevisionId].capabilities;const selection=(capabilities??configured).map(ref=>{const bound=configured.find(x=>x.id===ref.id&&x.kind===ref.kind&&x.revision===ref.revision);if(!bound)throw new Error('projects/capability-not-bound');return bound});const link:ProjectTaskLink={id:randomUUID(),projectId,sessionId:clean(sessionId),title:clean(title,'projects/invalid-title',500),configRevisionId:project.configRevisionId,capabilities:selection,...(workItemId?{workItemId}:{}),references:validated,createdAt:timestamp()};const activity=this.event(projectId,actor,'task',`创建任务「${link.title}」`);await this.put(actor,{...state,tasks:{...state.tasks,[link.id]:link},activity:{...state.activity,[activity.id]:activity}});return link;});}
  taskContext(actor:ActorContext,sessionId:string){return this.enqueue(async():Promise<ProjectTaskContext|undefined>=>{const state=await this.state(actor),task=Object.values(state.tasks).find(row=>row.sessionId===sessionId);if(!task)return undefined;const project=state.projects[task.projectId],config=state.configs[task.configRevisionId];if(!project||!config)return undefined;return{availableCapabilities:config.capabilities,project:this.normalizedProject(project),config:{...config,capabilities:task.capabilities??config.capabilities},task:{...task,references:task.references??[]}};});}
  noteDeliveryGap(actor:ActorContext,projectId:string,text:string){return this.enqueue(async()=>{const state=await this.state(actor);this.requireProject(state,projectId);const activity=this.event(projectId,actor,'asset',clean(text,'projects/invalid-title',500));await this.put(actor,{...state,activity:{...state.activity,[activity.id]:activity}});});}

  private listForStatus(actor:ActorContext,query:string,status:Project['status']){return this.enqueue(async()=>{const state=await this.state(actor),needle=query.trim().toLocaleLowerCase();return Object.values(state.projects).map(row=>this.normalizedProject(row)).filter(row=>row.status===status&&(!needle||`${row.name} ${row.description}`.toLocaleLowerCase().includes(needle))).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));});}
  private event(projectId:string,actor:ActorContext,kind:ProjectActivity['kind'],text:string):ProjectActivity{return{id:randomUUID(),projectId,kind,text,actorId:actor.principalId,createdAt:timestamp()};}
  private snapshot(state:Stored,project:Project):ProjectSnapshot{const config=state.configs[project.configRevisionId];if(!config)throw new Error('projects/not-found');const filter=<T extends {projectId:string}>(v:Record<string,T>)=>Object.values(v).filter(row=>row.projectId===project.id);return{project:this.normalizedProject(project),config,workItems:filter(state.workItems),assets:filter(state.assets),tasks:filter(state.tasks).map(row=>({...row,references:row.references??[]})),activity:filter(state.activity).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))};}
  private validateReferences(state:Stored,project:Project,references:readonly ProjectInputRef[]){const config=state.configs[project.configRevisionId],unique=new Map<string,ProjectInputRef>();for(const ref of references){const key=`${ref.kind}:${ref.id}`;if(unique.has(key))continue;if(ref.kind==='work-item'){const item=state.workItems[ref.id];if(!item||item.projectId!==project.id||item.revision!==ref.revision)throw new Error('projects/reference-stale');}else if(ref.kind==='asset'){const asset=state.assets[ref.id];if(!asset||asset.projectId!==project.id||asset.revisionId!==ref.revision)throw new Error('projects/reference-stale');}else{const skill=config?.capabilities.find(row=>row.kind==='skill'&&row.id===ref.id);if(!skill||(skill.revision??project.configRevisionId)!==ref.revision)throw new Error('projects/reference-stale');}unique.set(key,{...ref,label:clean(ref.label,'projects/invalid-title',500)});}return[...unique.values()];}
  private normalizedProject(project:Project):Project{return{...project,description:project.description??''};}
  private requireProject(state:Stored,id:string){const row=state.projects[id];if(!row||row.status==='archived')throw new Error('projects/not-found');return this.normalizedProject(row);}
  private async state(actor:ActorContext):Promise<Stored>{const key=projectStateKey(actor.organizationId,actor.principalId),found=await this.states().get(key);if(found)return found as Stored;const state:Stored={schemaVersion:1,projects:{},configs:{},workItems:{},assets:{},tasks:{},activity:{}};await this.states().put(key,state);return state;}
  private put(actor:ActorContext,state:Stored){return this.states().put(projectStateKey(actor.organizationId,actor.principalId),state);}
  private states(){if(!this.table)throw new Error('projects/not-ready');return this.table;}
  private enqueue<T>(work:()=>Promise<T>):Promise<T>{const next=this.serial.then(work,work);this.serial=next.then(()=>undefined,()=>undefined);return next;}
}
